services:
  monzowler.api:
    image: monzowler.api
    build:
      context: .
      dockerfile: src/Monzowler.Api/Dockerfile
  
  localstack:
    image: localstack/localstack
    ports:
      - "4566:4566"
    environment:
      - SERVICES=dynamodb
      - DEFAULT_REGION=us-east-1

  awscli:
    image: amazon/aws-cli
    depends_on:
      - localstack
    entrypoint: |
      sh -c "
        aws --endpoint-url=http://localstack:4566 dynamodb create-table \
          --table-name Sitemap \
          --attribute-definitions AttributeName=Url,AttributeType=S \
          --key-schema AttributeName=Url,KeyType=HASH \
          --billing-mode PAY_PER_REQUEST;
      "

