services:
  monzowler:
    build:
      context: .
      dockerfile: src/Monzowler.Api/Dockerfile
    depends_on:
      - localstack
    networks:
      - default
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://*:5000
      - AWS_REGION=us-east-1
      - AWS_ACCESS_KEY_ID=XX
      - AWS_SECRET_ACCESS_KEY=XX
    ports:
      - "5000:5000"
  
  localstack:
    image: localstack/localstack:latest
    container_name: localstack
    environment:
      - SERVICES=dynamodb
      - HOSTNAME=localstack
      - DEFAULT_REGION=us-east-1
    ports:
      - "4566:4566"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock" 
    healthcheck:
      test: curl http://localhost:4566/_localstack/health -sb --fail | grep available
      interval: 1s
      retries: 100
      start_period: 1s
      timeout: 1s

  monzowler-awscli:
    image: garland/aws-cli-docker:latest
    networks:
      - default
    container_name: monzowler-awscli
    depends_on:
      localstack:
        condition: service_healthy
    environment:
      - AWS_DEFAULT_REGION=us-east-1
      - AWS_ACCESS_KEY_ID=XX
      - AWS_SECRET_ACCESS_KEY=XX
    command: 
      - /bin/sh
      - -c
      - |
        aws --endpoint-url=http://localstack:4566 dynamodb create-table \
        --table-name Crawler-Sitemap \
        --attribute-definitions \
          AttributeName=Domain,AttributeType=S \
          AttributeName=PageUrl,AttributeType=S \
        --key-schema \
          AttributeName=Domain,KeyType=HASH \
          AttributeName=PageUrl,KeyType=RANGE \
        --billing-mode PAY_PER_REQUEST
        
networks:
  default:
    name: localstack
    ipam:
      config:
        - subnet: 172.24.3.0/24