services:
  monzowler:
    build:
      context: .
      dockerfile: src/Monzowler.Api/Dockerfile
    depends_on:
      - localstack
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://*:5000
      - AWS_REGION=us-east-1
      - AWS_ACCESS_KEY_ID=XX
      - AWS_SECRET_ACCESS_KEY=XX
    ports:
      - "5000:5000"
  
  localstack:
    image: localstack/localstack
    ports:
      - "4566:4566"
    container_name: localstack
    environment:
      - SERVICES=dynamodb
      - HOSTNAME=localstack
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock" 
    healthcheck:
      test: curl http://localhost:4566/_localstack/health -sb --fail | grep available
      interval: 1s
      retries: 100
      start_period: 1s
      timeout: 1s

  monzowler-awscli:
    image: garland/aws-cli-docker:latest
    container_name: monzowler-awscli
    depends_on:
      localstack:
        condition: service_healthy
    environment:
      - AWS_DEFAULT_REGION=us-east-1
      - AWS_ACCESS_KEY_ID=XX
      - AWS_SECRET_ACCESS_KEY=XX
    entrypoint: >
      sh -c "
        sleep 10 && \
        aws --endpoint-url=http://localstack:4566 dynamodb create-table \
          --table-name Sitemap \
          --attribute-definitions AttributeName=PK,AttributeType=S AttributeName=SK,AttributeType=S \
          --key-schema AttributeName=PK,KeyType=HASH AttributeName=SK,KeyType=RANGE \
          --billing-mode PAY_PER_REQUEST
      "

