services:
  localstack:
    image: localstack/localstack:latest
    container_name: localstack
    environment:
      - SERVICES=dynamodb
      - HOSTNAME=localstack
      - DEFAULT_REGION=us-east-1
    ports:
      - "4566:4566"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    healthcheck:
      test: curl http://localhost:4566/_localstack/health -sb --fail | grep available
      interval: 1s
      retries: 100
      start_period: 1s
      timeout: 1s

  awscli:
    image: garland/aws-cli-docker:latest
    networks:
      - default
    container_name: awscli
    depends_on:
      localstack:
        condition: service_healthy
    environment:
      - AWS_DEFAULT_REGION=us-east-1
      - AWS_ACCESS_KEY_ID=XX
      - AWS_SECRET_ACCESS_KEY=XX
    command:
      - /bin/sh
      - -c
      - |
        aws --endpoint-url=http://localstack:4566 dynamodb create-table \
        --table-name Crawler-Sitemap \
        --attribute-definitions \
        AttributeName=Domain,AttributeType=S \
        AttributeName=PageUrl,AttributeType=S \
        AttributeName=JobId,AttributeType=S \
        --key-schema \
        AttributeName=Domain,KeyType=HASH \
        AttributeName=PageUrl,KeyType=RANGE \
        --provisioned-throughput ReadCapacityUnits=10,WriteCapacityUnits=5 \
        --global-secondary-indexes \
        '[
            {
              "IndexName": "GSI_JobId",
              "KeySchema": [
                {"AttributeName": "JobId", "KeyType": "HASH"}
              ],
              "Projection": {
                "ProjectionType": "ALL"
              },
              "ProvisionedThroughput": {
                "ReadCapacityUnits": 5,
                "WriteCapacityUnits": 5
              }
            }
          ]' \
        --billing-mode PROVISIONED
        
        aws --endpoint-url=http://localstack:4566 dynamodb create-table \
        --table-name Crawler-Jobs \
        --attribute-definitions AttributeName=JobId,AttributeType=S \
        --key-schema AttributeName=JobId,KeyType=HASH \
        --billing-mode PAY_PER_REQUEST

networks:
  default:
    name: localstack
    ipam:
      config:
        - subnet: 172.24.3.0/24