### --- CREATE JOB CRAWL ---
POST http://localhost:5002/crawl
Content-Type: application/json

{
  "url": "https://monzo.com",
  "maxDepth": 2,
  "maxRetries": 2
}

### --- JOB GET ---
GET http://localhost:5002/crawl/94aa7ba3-289d-4b7a-8e5b-ca28ca0b8081
Content-Type: application/json

{}

### --- SITEMAP JOB GET ---
GET http://localhost:5002/crawl/sitemap/f2e4b922-22b3-469e-b363-4703cfeaa616
Content-Type: application/json

{}